package VTiger.GeneralUtilities;

import java.io.IOException;

import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;

import com.aventstack.extentreports.ExtentReports;
import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import com.aventstack.extentreports.reporter.ExtentSparkReporter;
import com.aventstack.extentreports.reporter.configuration.Theme;

/**
 * This class will implementation to ITestListener interface of TestNG
 * This is an example for abstraction 
 * @author HP
 *
 */

public class ListenerImplementationClass implements ITestListener 
{
	
	ExtentReports report;
	ExtentTest test;

	public void onTestStart(ITestResult result) {
		// TODO Auto-generated method stub
		String methodName = result.getMethod().getMethodName();
		System.out.println("-------Execution started---" +methodName);
		
		test=report.createTest(methodName);
	}

	public void onTestSuccess(ITestResult result) {
		// TODO Auto-generated method stub
		String methodName = result.getMethod().getMethodName();
		//System.out.println("-------PASS---" +methodName);
		test.log(Status.PASS, "-------PASS---" +methodName);
	}

	public void onTestFailure(ITestResult result) {
		// TODO Auto-generated method stub
		String methodName = result.getMethod().getMethodName();
		//System.out.println("-------FAIL---" +methodName);
		
		test.log(Status.FAIL, "-------FAIL---" +methodName);
		
		System.out.println(result.getThrowable()); //this will print the exception 
		
		test.log(Status.INFO, result.getThrowable());
		
		WebDriverUtility wUtil=new WebDriverUtility();
		JavaUtility jUtil=new JavaUtility(); // to get date of local system 
		
		String Screenshot = methodName+jUtil.getSystemDateInFormat();
		//autogenerated try & catch block
		try {
			String path = wUtil.screenshot(BaseClass.sdriver, methodName);
			test.addScreenCaptureFromPath(path);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	public void onTestSkipped(ITestResult result) {
		// TODO Auto-generated method stub
		String methodName = result.getMethod().getMethodName();
		//System.out.println("-------SKIP---" +methodName);
		
		test.log(Status.SKIP, "--- SKIP --- "+methodName);
		
	}

	public void onTestFailedButWithinSuccessPercentage(ITestResult result) {
		// TODO Auto-generated method stub
		
	}

	public void onTestFailedWithTimeout(ITestResult result) {
		// TODO Auto-generated method stub
	
	}

	public void onStart(ITestContext context) {
		// start of suite act like @Beforesuit
		System.out.println("-----Suit execution started----");
		
		//configure the extent report 
		ExtentSparkReporter htmlReport= new ExtentSparkReporter(".ExtentReports\\Report-"+new JavaUtility().getSystemDateInFormat());
		htmlReport.config().setDocumentTitle("vTiger Execution report");
		htmlReport.config().setReportName("Build 3 vTiger Execution report");
		htmlReport.config().setTheme(Theme.DARK);
		
		//Report generation 
		report=new ExtentReports();
		report.attachReporter(htmlReport);
		report.setSystemInfo("Browser", "chrome");
		report.setSystemInfo("Base platform", "Test_Environment");
		report.setSystemInfo("Base URL", "http://localhost:8888/");
		report.setSystemInfo("Base OS", "Windows");
		report.setSystemInfo("Reporter", "Shilpa");
		
	}

	public void onFinish(ITestContext context) {
		// end of suite act like @Aftersuit
		System.out.println("-----Suit execution ended----");
		
		//Report Generation
				report.flush();
	}

}
